import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "admin-panel",
  description: "Generated by Layout Builder",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
