export default function Home() {
  return (
    <div style={{ padding: "2rem", fontFamily: "system-ui" }}>
      <h1 style={{ fontSize: "2.5rem", marginBottom: "1rem" }}>
        Welcome to admin-panel!
      </h1>
      <p style={{ fontSize: "1.2rem", color: "#666" }}>
        This app was generated by the Layout Builder.
      </p>
      <div style={{ marginTop: "2rem" }}>
        <a 
          href="/layouts" 
          style={{ 
            padding: "0.75rem 1.5rem", 
            background: "#0070f3", 
            color: "white", 
            textDecoration: "none",
            borderRadius: "0.5rem",
            display: "inline-block"
          }}
        >
          View Layouts
        </a>
      </div>
    </div>
  );
}
