import * as fs from "fs";
import * as path from "path";

interface ScaffoldOptions {
  appId: string;
  appName: string;
  description: string;
  type: "nextjs" | "express";
}

// Get the root directory of the monorepo
const getMonorepoRoot = (): string => {
  // Navigate up from backend/src/services to the monorepo root
  return path.resolve(__dirname, "../../../..");
};

// Create package.json for Next.js app
const createNextJsPackageJson = (appId: string, appName: string): string => {
  return JSON.stringify(
    {
      name: appId,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev --port 3001",
        build: "next build",
        start: "next start",
        lint: "next lint",
        clean: "rm -rf .next .turbo node_modules",
      },
      dependencies: {
        next: "14.2.0",
        react: "^18.3.0",
        "react-dom": "^18.3.0",
      },
      devDependencies: {
        "@repo/typescript-config": "workspace:*",
        "@types/node": "^20",
        "@types/react": "^18",
        "@types/react-dom": "^18",
        eslint: "^8",
        "eslint-config-next": "14.2.0",
        typescript: "^5",
      },
    },
    null,
    2
  );
};

// Create tsconfig.json for Next.js app
const createNextJsTsConfig = (): string => {
  return JSON.stringify(
    {
      extends: "@repo/typescript-config/nextjs.json",
      compilerOptions: {
        plugins: [{ name: "next" }],
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2
  );
};

// Create next.config.mjs
const createNextConfig = (): string => {
  return `/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;
`;
};

// Create layout.tsx
const createLayout = (appName: string): string => {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${appName}",
  description: "Generated by Layout Builder",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
};

// Create page.tsx
const createPage = (appName: string): string => {
  return `export default function Home() {
  return (
    <div style={{ padding: "2rem", fontFamily: "system-ui" }}>
      <h1 style={{ fontSize: "2.5rem", marginBottom: "1rem" }}>
        Welcome to ${appName}!
      </h1>
      <p style={{ fontSize: "1.2rem", color: "#666" }}>
        This app was generated by the Layout Builder.
      </p>
      <div style={{ marginTop: "2rem" }}>
        <a 
          href="/layouts" 
          style={{ 
            padding: "0.75rem 1.5rem", 
            background: "#0070f3", 
            color: "white", 
            textDecoration: "none",
            borderRadius: "0.5rem",
            display: "inline-block"
          }}
        >
          View Layouts
        </a>
      </div>
    </div>
  );
}
`;
};

// Create globals.css
const createGlobalsCss = (): string => {
  return `* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

html,
body {
  max-width: 100vw;
  overflow-x: hidden;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
    "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

a {
  color: inherit;
  text-decoration: none;
}
`;
};

// Create README.md
const createReadme = (appName: string, appId: string): string => {
  return `# ${appName}

This is a Next.js application generated by the Layout Builder.

## Getting Started

First, run the development server:

\`\`\`bash
cd apps/${appId}
pnpm dev
\`\`\`

Open [http://localhost:3001](http://localhost:3001) with your browser to see the result.

## Features

- ✅ Next.js 14
- ✅ TypeScript
- ✅ ESLint
- ✅ Shared TypeScript config
- ✅ Ready for layout integration

## Generated Layouts

Your generated layouts will appear in the \`src/app/layouts\` directory.

## Learn More

To learn more about Next.js, take a look at the following resources:

- [Next.js Documentation](https://nextjs.org/docs)
- [Learn Next.js](https://nextjs.org/learn)
`;
};

// Main scaffolding function
export const scaffoldApp = async (options: ScaffoldOptions): Promise<void> => {
  const { appId, appName, type } = options;

  if (type !== "nextjs") {
    throw new Error("Only Next.js apps are supported at this time");
  }

  const monorepoRoot = getMonorepoRoot();
  const appDir = path.join(monorepoRoot, "apps", appId);

  // Check if app already exists
  if (fs.existsSync(appDir)) {
    throw new Error(`App directory already exists: apps/${appId}`);
  }

  try {
    // Create main app directory
    fs.mkdirSync(appDir, { recursive: true });

    // Create package.json
    fs.writeFileSync(
      path.join(appDir, "package.json"),
      createNextJsPackageJson(appId, appName)
    );

    // Create tsconfig.json
    fs.writeFileSync(path.join(appDir, "tsconfig.json"), createNextJsTsConfig());

    // Create next.config.mjs
    fs.writeFileSync(path.join(appDir, "next.config.mjs"), createNextConfig());

    // Create README.md
    fs.writeFileSync(path.join(appDir, "README.md"), createReadme(appName, appId));

    // Create src directory structure
    const srcDir = path.join(appDir, "src");
    fs.mkdirSync(srcDir, { recursive: true });

    // Create src/app directory
    const appSrcDir = path.join(srcDir, "app");
    fs.mkdirSync(appSrcDir, { recursive: true });

    // Create layout.tsx
    fs.writeFileSync(path.join(appSrcDir, "layout.tsx"), createLayout(appName));

    // Create page.tsx
    fs.writeFileSync(path.join(appSrcDir, "page.tsx"), createPage(appName));

    // Create globals.css
    fs.writeFileSync(path.join(appSrcDir, "globals.css"), createGlobalsCss());

    // Create public directory
    const publicDir = path.join(appDir, "public");
    fs.mkdirSync(publicDir, { recursive: true });

    console.log(`✅ Successfully scaffolded app: ${appId}`);
  } catch (error) {
    // Clean up on error
    if (fs.existsSync(appDir)) {
      fs.rmSync(appDir, { recursive: true, force: true });
    }
    throw error;
  }
};

// Update turbo.json to include new app
export const updateTurboConfig = async (appId: string): Promise<void> => {
  const monorepoRoot = getMonorepoRoot();
  const turboConfigPath = path.join(monorepoRoot, "turbo.json");

  // Note: turbo.json doesn't need to be updated as it uses workspace patterns
  // The app will automatically be picked up by the workspace configuration
  console.log(`✅ App ${appId} will be auto-discovered by Turborepo`);
};

// Update pnpm-workspace.yaml (if needed)
export const updateWorkspaceConfig = async (): Promise<void> => {
  // The workspace already includes "apps/*" so no update needed
  console.log(`✅ Workspace config already includes apps/*`);
};

export interface ScaffoldResult {
  success: boolean;
  appId: string;
  appPath: string;
  message: string;
  nextSteps: string[];
}

export const createNewApp = async (
  appId: string,
  appName: string,
  description: string
): Promise<ScaffoldResult> => {
  try {
    await scaffoldApp({
      appId,
      appName,
      description,
      type: "nextjs",
    });

    await updateTurboConfig(appId);
    await updateWorkspaceConfig();

    return {
      success: true,
      appId,
      appPath: `apps/${appId}`,
      message: `Successfully created ${appName}!`,
      nextSteps: [
        `cd apps/${appId}`,
        "pnpm install",
        "pnpm dev",
        `Open http://localhost:3001`,
      ],
    };
  } catch (error) {
    return {
      success: false,
      appId,
      appPath: `apps/${appId}`,
      message: error instanceof Error ? error.message : "Failed to create app",
      nextSteps: [],
    };
  }
};

